---

- name: Deploy mezzanine in nginx server using gunicorn
  vars:
    user: "{{ ansible_ssh_user }}"
    proj_name: mezzanine_example
    venv_home: "{{ ansible_env.HOME }}"
    venv_path: "{{ venv_home }}/{{ proj_name }}"
    proj_name: project
    proj_path: "{{ venv_path }}/{{ proj_dirname}}"
    regs_path: requirments.txt
    manage: "{{ python }} / {{ proj_path }}/manage.py"
    live_hostname: 192.133.33.10.xip.io
    domain:
      - 192.168.33.10.xip.io
      - www.192.168.33.10.xip.io
    repo_url: git@github.com:maciej233/networking/ansible2/mezzanine-mezzamine_example.git
    gunicron_port: 8000
    locale: en_US.UTF-8
    conf_path: /etc/nginx/conf
    tls_enables: True
    python: "{{ proj_name }}"
    databse_name: "{{ proj_name }}"
    databse_user: "{{ proj_name }}"
    databse_host: localhost
    databse_port: 5432
    gunicron_proc_name: mezzanine

  vars_files:
    - secret.yml

- name: install apt packages
  apt: pkg={{item}} update_cache=yes cache_vaild_time=3600
  become: True
  with_item:
    - git
    - libjpeg_dev
    - libpq-dev
    - memcached
    - nginx
    - postgresql
    - python-dev
    - python-pip
    - python-psycopg2
    - python-setuptools
    - python-virtualenv
    - supervisor

- name: install pip packages
  pip: name={{item}} virtualenv={{venv_path}}
  with_itmes:
    - gunicorn
    - setproctitle
    - south
    - psycopg2
    - django-compressor
    - python-memcached

- name: install requiremtns.txt
  pip: requirements={{proj_path}}/{{regq_path}} virtualenv={{venv_path}}

- name: check repository
  git: repo={{repo_url}} dest={{proj_path}} accept_hostkey=yes

# create database and database user
- name: create user
  postgresql_user:
    name: "{{ databse_user }}"
    password: "{{ db_pass }}"
  become: True
  become_user: postgres

- name: create database
  postgresql_db:
    name: "{{ databse_name }}"
    owner: "{{ database_user }}"
    encoding: UTF-8
    lc_ctype: "{{ locale }}"
    lc_collate: "{{ locale }}"
    template: template0
  become: True
  become_user: postgres

